### ISSUE TITLE
[FEATURE] Add support to MacOS

### ISSUE THREAD

**Issue by rignaneseleo** [bugfender/BugfenderSDK-Flutter#40]
Please add support to MacOS so that we can use the library on that platform too.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method sendCrash on channel flutter_bugfender)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelFlutterBugfender.sendCrash.<anonymous closure> (package:flutter_bugfender/flutter_bugfender_method_channel.dart:79:13)
<asynchronous suspension>
#2      FlutterBugfender.handleUncaughtErrors.<anonymous closure> (package:flutter_bugfender/flutter_bugfender.dart:83:7)
<asynchronous suspension>
```

**Comment by rignaneseleo** [comment]
I think the right behavior here for such a library should be to print a warning and keep going on, ignoring all the remote logs.
